"""corrige default de status para pendente

Revision ID: 2cc774672704
Revises: ba7771d00ae9
Create Date: 2026-07-13 09:27:49.203493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cc774672704'
down_revision: Union[str, Sequence[str], None] = 'ba7771d00ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('baia360_users', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default='pendente',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('baia360_users', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'ativo'::character varying"),
               existing_nullable=True)
    # ### end Alembic commands ###
