"""baseline: schema atual

Revision ID: 31b9745f3ba2
Revises: 
Create Date: 2026-07-10 09:59:06.917655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b9745f3ba2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atlas_golden_qa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pergunta', sa.Text(), nullable=False),
    sa.Column('resposta_ref', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atlas_golden_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=50), nullable=True),
    sa.Column('n_perguntas', sa.Integer(), nullable=True),
    sa.Column('mean_faith', sa.Float(), nullable=True),
    sa.Column('mean_answer', sa.Float(), nullable=True),
    sa.Column('mean_context', sa.Float(), nullable=True),
    sa.Column('mean_ground', sa.Float(), nullable=True),
    sa.Column('custo_estimado', sa.Float(), nullable=True),
    sa.Column('detalhe_json', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('baia360_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=256), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('atlas_acao_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tool', sa.String(length=50), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('args_hash', sa.String(length=64), nullable=False),
    sa.Column('destinatario', sa.String(length=255), nullable=True),
    sa.Column('externo', sa.Boolean(), nullable=False),
    sa.Column('origem', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criada_em', sa.DateTime(), nullable=True),
    sa.Column('executada_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['baia360_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_table('atlas_instrucao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('atualizada_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['baia360_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('atlas_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('primeira_msg', sa.String(length=200), nullable=True),
    sa.Column('total_msgs', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['baia360_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atlas_memoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('criada_em', sa.DateTime(), nullable=True),
    sa.Column('atualizada_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['baia360_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atlas_projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['baia360_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atlas_rag_trace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('conv_id', sa.String(length=20), nullable=True),
    sa.Column('response_id', sa.String(length=80), nullable=True),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('pergunta', sa.Text(), nullable=True),
    sa.Column('resposta', sa.Text(), nullable=True),
    sa.Column('usou_file_search', sa.Boolean(), nullable=True),
    sa.Column('retrieval_query', sa.Text(), nullable=True),
    sa.Column('retrieval_count', sa.Integer(), nullable=True),
    sa.Column('top_score', sa.Float(), nullable=True),
    sa.Column('mean_score', sa.Float(), nullable=True),
    sa.Column('zero_retrieval', sa.Boolean(), nullable=True),
    sa.Column('chunks_json', sa.Text(), nullable=True),
    sa.Column('n_file_citations', sa.Integer(), nullable=True),
    sa.Column('citation_coverage', sa.Boolean(), nullable=True),
    sa.Column('feedback', sa.String(length=10), nullable=True),
    sa.Column('groundedness', sa.Float(), nullable=True),
    sa.Column('eval_faithfulness', sa.Float(), nullable=True),
    sa.Column('eval_answer_rel', sa.Float(), nullable=True),
    sa.Column('eval_context_rel', sa.Float(), nullable=True),
    sa.Column('eval_flagged', sa.Boolean(), nullable=True),
    sa.Column('eval_modelo', sa.String(length=50), nullable=True),
    sa.Column('latencia_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['baia360_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atlas_rag_trace_conv_id'), 'atlas_rag_trace', ['conv_id'], unique=False)
    op.create_index(op.f('ix_atlas_rag_trace_criado_em'), 'atlas_rag_trace', ['criado_em'], unique=False)
    op.create_index(op.f('ix_atlas_rag_trace_eval_flagged'), 'atlas_rag_trace', ['eval_flagged'], unique=False)
    op.create_index(op.f('ix_atlas_rag_trace_feedback'), 'atlas_rag_trace', ['feedback'], unique=False)
    op.create_index(op.f('ix_atlas_rag_trace_response_id'), 'atlas_rag_trace', ['response_id'], unique=False)
    op.create_index(op.f('ix_atlas_rag_trace_usou_file_search'), 'atlas_rag_trace', ['usou_file_search'], unique=False)
    op.create_index(op.f('ix_atlas_rag_trace_usuario_id'), 'atlas_rag_trace', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_atlas_rag_trace_zero_retrieval'), 'atlas_rag_trace', ['zero_retrieval'], unique=False)
    op.create_table('outlook_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('email_outlook', sa.String(length=120), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['baia360_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('permissoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('hub_json', sa.Text(), nullable=False),
    sa.Column('modulos_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['baia360_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('relatorios_gerados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('mes_ref', sa.String(length=10), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('gerado_em', sa.DateTime(), nullable=True),
    sa.Column('kpis_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['baia360_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atlas_conversas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('conv_id', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('msgs_json', sa.Text(), nullable=False),
    sa.Column('history_json', sa.Text(), nullable=False),
    sa.Column('atualizada_em', sa.DateTime(), nullable=True),
    sa.Column('pinada', sa.Boolean(), nullable=True),
    sa.Column('criada_em', sa.DateTime(), nullable=True),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['atlas_projetos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['baia360_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atlas_conversas')
    op.drop_table('relatorios_gerados')
    op.drop_table('permissoes')
    op.drop_table('outlook_tokens')
    op.drop_index(op.f('ix_atlas_rag_trace_zero_retrieval'), table_name='atlas_rag_trace')
    op.drop_index(op.f('ix_atlas_rag_trace_usuario_id'), table_name='atlas_rag_trace')
    op.drop_index(op.f('ix_atlas_rag_trace_usou_file_search'), table_name='atlas_rag_trace')
    op.drop_index(op.f('ix_atlas_rag_trace_response_id'), table_name='atlas_rag_trace')
    op.drop_index(op.f('ix_atlas_rag_trace_feedback'), table_name='atlas_rag_trace')
    op.drop_index(op.f('ix_atlas_rag_trace_eval_flagged'), table_name='atlas_rag_trace')
    op.drop_index(op.f('ix_atlas_rag_trace_criado_em'), table_name='atlas_rag_trace')
    op.drop_index(op.f('ix_atlas_rag_trace_conv_id'), table_name='atlas_rag_trace')
    op.drop_table('atlas_rag_trace')
    op.drop_table('atlas_projetos')
    op.drop_table('atlas_memoria')
    op.drop_table('atlas_logs')
    op.drop_table('atlas_instrucao')
    op.drop_table('atlas_acao_log')
    op.drop_table('baia360_users')
    op.drop_table('atlas_golden_run')
    op.drop_table('atlas_golden_qa')
    # ### end Alembic commands ###
